import React, { useState } from 'react';
import { Ship, Wind, Code, Github } from 'lucide-react'; // Minimalist icons
import { shipToGithub } from '../lib/agent'; // The JS we wrote earlier

export default function FreshAssistant() {
  const [prompt, setPrompt] = useState("");
  const [isShipping, setIsShipping] = useState(false);
  const [logs, setLogs] = useState(["🍃 FreshAI initialized... Ready for krovixa."]);

  const addLog = (msg) => setLogs(prev => [`> ${msg}`, ...prev.slice(0, 5)]);

  const handleAction = async (type) => {
    setIsShipping(true);
    addLog(`Initiating ${type} sequence...`);
    
    // In a real setup, your AI logic would generate the 'code' string here
    const mockCode = `// Generated by FreshAI\nexport const MyComponent = () => <div>Hello World</div>;`;
    
    const result = await shipToGithub("src/components/Generated.jsx", mockCode, `feat: ${type} from FreshAI`);
    
    addLog(result);
    setIsShipping(false);
  };

  return (
    <div className="flex flex-col h-screen bg-[#0a0a0a] text-[#e0e0e0] font-sans p-6">
      {/* Header */}
      <header className="flex justify-between items-center mb-8 border-b border-white/10 pb-4">
        <div className="flex items-center gap-2">
          <Wind className="text-emerald-400" size={28} />
          <h1 className="text-xl font-bold tracking-tight">FreshAI <span className="text-xs font-normal opacity-50 px-2 border border-white/20 rounded-full ml-2">v1.0</span></h1>
        </div>
        <div className="flex items-center gap-4 text-sm opacity-70">
          <span className="flex items-center gap-1"><Github size={14}/> lupsup39</span>
          <span className="bg-emerald-500/10 text-emerald-400 px-2 py-0.5 rounded">Connected: CodeSandbox</span>
        </div>
      </header>

      {/* Main Workspace */}
      <main className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Input Area */}
        <div className="bg-[#111] border border-white/5 rounded-xl p-4 flex flex-col shadow-2xl">
          <label className="text-xs uppercase tracking-widest text-emerald-400 mb-2 font-bold">Designer Intent</label>
          <textarea 
            className="flex-1 bg-transparent resize-none outline-none text-lg leading-relaxed placeholder:opacity-20"
            placeholder="Describe a responsive navbar with a glassmorphism effect..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
          />
          <div className="flex gap-3 mt-4">
            <button 
              onClick={() => handleAction('Build')}
              className="flex-1 bg-white text-black font-bold py-3 rounded-lg flex items-center justify-center gap-2 hover:bg-emerald-400 transition"
              disabled={isShipping}
            >
              <Code size={18} /> Build Logic
            </button>
            <button 
              onClick={() => handleAction('Push')}
              className="px-6 bg-emerald-600 hover:bg-emerald-500 rounded-lg flex items-center justify-center transition"
              disabled={isShipping}
            >
              <Ship size={18} />
            </button>
          </div>
        </div>

        {/* Live Logs & Preview */}
        <div className="flex flex-col gap-6">
          <div className="h-1/2 bg-black border border-white/5 rounded-xl p-4 font-mono text-sm">
             <div className="text-xs text-white/30 mb-2 uppercase">System Logs</div>
             {logs.map((log, i) => (
               <div key={i} className={log.includes('✅') ? "text-emerald-400" : "text-white/60"}>{log}</div>
             ))}
          </div>
          <div className="flex-1 bg-[#111] border border-white/5 rounded-xl p-4 flex items-center justify-center border-dashed border-white/20">
            <p className="text-white/20 text-sm italic">Live Preview Component Area</p>
          </div>
        </div>
      </main>
    </div>
  );
}
